2023-04-19 21:40:48,105 - Service.LoggerContext.scrape_link() on line 14 - INFO - Starting Scraping https://www.op.gg/. . .
2023-04-19 21:40:49,660 - Service.LoggerContext.scrape_link() on line 18 - INFO - Scraping Success!
2023-04-19 21:40:58,408 - Service.LoggerContext.scrape_link() on line 14 - INFO - Starting Scraping https://www.aasdsdop.gg/. . .
2023-04-19 21:40:58,543 - Service.LoggerContext.__get_raw_html_from_link() on line 32 - WARNING - Failed with: HTTPSConnectionPool(host='www.aasdsdop.gg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000261624AF860>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2023-04-19 21:40:58,543 - Service.LoggerContext.__get_raw_html_from_link() on line 38 - INFO - Will try again with non-secure connection ...
2023-04-19 21:40:58,544 - Service.LoggerContext.scrape_link() on line 21 - ERROR - Scraping Failed . . .
2023-04-19 21:41:51,629 - Service.LoggerContext.scrape_link() on line 14 - INFO - Starting Scraping https://www.aasdsdop.gg/. . .
2023-04-19 21:41:51,780 - Service.LoggerContext.__get_raw_html_from_link() on line 32 - WARNING - Failed with: HTTPSConnectionPool(host='www.aasdsdop.gg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002195B8DFF98>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2023-04-19 21:41:51,782 - Service.LoggerContext.__get_raw_html_from_link() on line 38 - INFO - Will try again with non-secure connection ...
2023-04-19 21:41:51,782 - Service.LoggerContext.scrape_link() on line 21 - CRITICAL - Scraping Failed . . .
2023-04-19 21:41:51,782 - Service.LoggerContext.main() on line 15 - ERROR - HTTPSConnectionPool(host='www.aasdsdop.gg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002195B8DFF98>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2023-04-19 21:42:43,979 - Service.LoggerContext.scrape_link() on line 14 - INFO - Starting Scraping https://www.aasdsdop.gg/. . .
2023-04-19 21:42:44,118 - Service.LoggerContext.__get_raw_html_from_link() on line 32 - WARNING - Failed with: HTTPSConnectionPool(host='www.aasdsdop.gg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FB64460F28>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2023-04-19 21:42:44,118 - Service.LoggerContext.__get_raw_html_from_link() on line 33 - WARNING - Will try again with non-secure connection ...
2023-04-19 21:42:44,119 - Service.LoggerContext.scrape_link() on line 21 - CRITICAL - Scraping Failed . . .
2023-04-19 21:42:44,119 - Service.LoggerContext.main() on line 15 - ERROR - HTTPSConnectionPool(host='www.aasdsdop.gg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FB62874B00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2023-04-19 21:47:04,131 - Service.LoggerContext.scrape_link() on line 14 - INFO - Starting Scraping https://www.aasdsdop.gg/. . .
2023-04-19 21:47:04,184 - Service.LoggerContext.__get_raw_html_from_link() on line 32 - WARNING - Failed with: HTTPSConnectionPool(host='www.aasdsdop.gg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002548F8D3A20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2023-04-19 21:47:04,184 - Service.LoggerContext.__get_raw_html_from_link() on line 33 - WARNING - Will try again with non-secure connection ...
2023-04-19 21:47:04,185 - Service.LoggerContext.scrape_link() on line 21 - CRITICAL - Scraping Failed . . .
2023-04-19 21:47:04,185 - Service.LoggerContext.main() on line 15 - ERROR - HTTPSConnectionPool(host='www.aasdsdop.gg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002548DF846D8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2023-04-19 23:58:26,779 - Service.LoggerContext.scrape_link() on line 14 - INFO - Starting Scraping https://www.aasdsdop.gg/. . .
2023-04-19 23:58:26,817 - Service.LoggerContext.__get_raw_html_from_link() on line 32 - WARNING - Failed with: HTTPSConnectionPool(host='www.aasdsdop.gg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A32980E0F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2023-04-19 23:58:26,817 - Service.LoggerContext.__get_raw_html_from_link() on line 33 - WARNING - Will try again with non-secure connection ...
2023-04-19 23:58:26,817 - Service.LoggerContext.scrape_link() on line 21 - CRITICAL - Scraping Failed . . .
2023-04-19 23:58:26,818 - Service.LoggerContext.main() on line 15 - ERROR - HTTPSConnectionPool(host='www.aasdsdop.gg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3296CF8D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2023-04-19 23:59:44,328 - Service.LoggerContext.test() on line 11 - INFO - got profile id: 1
2023-04-20 00:03:01,060 - Service.LoggerContext.test() on line 16 - INFO - got profile id: 1
2023-04-20 00:11:24,888 - Service.LoggerContext.get_jobs_from_profile_id() on line 27 - ERROR - The current Flask app is not registered with this 'SQLAlchemy' instance. Did you forget to call 'init_app', or did you create multiple 'SQLAlchemy' instances?
2023-04-20 00:26:19,586 - Service.LoggerContext.get_jobs_from_profile_id() on line 26 - ERROR - The current Flask app is not registered with this 'SQLAlchemy' instance. Did you forget to call 'init_app', or did you create multiple 'SQLAlchemy' instances?
2023-04-20 00:26:51,030 - Service.LoggerContext.get_jobs_from_profile_id() on line 26 - ERROR - The current Flask app is not registered with this 'SQLAlchemy' instance. Did you forget to call 'init_app', or did you create multiple 'SQLAlchemy' instances?
2023-04-20 00:27:31,900 - Service.LoggerContext.get_jobs_from_profile_id() on line 26 - ERROR - The current Flask app is not registered with this 'SQLAlchemy' instance. Did you forget to call 'init_app', or did you create multiple 'SQLAlchemy' instances?
2023-04-20 00:29:30,417 - Service.LoggerContext.get_jobs_from_profile_id() on line 26 - ERROR - The current Flask app is not registered with this 'SQLAlchemy' instance. Did you forget to call 'init_app', or did you create multiple 'SQLAlchemy' instances?
2023-04-20 00:41:44,533 - Service.LoggerContext.get_jobs_from_profile_id() on line 26 - ERROR - Object of type Job is not JSON serializable
2023-04-20 00:42:00,460 - Service.LoggerContext.get_jobs_from_profile_id() on line 26 - ERROR - Object of type Job is not JSON serializable
2023-04-20 00:42:05,006 - Service.LoggerContext.get_jobs_from_profile_id() on line 26 - ERROR - Object of type Job is not JSON serializable
2023-04-20 00:50:57,139 - Service.LoggerContext.get_jobs_from_profile_id() on line 26 - ERROR - Object of type Job is not JSON serializable
2023-04-20 00:51:10,032 - Service.LoggerContext.get_jobs_from_profile_id() on line 26 - ERROR - Object of type Job is not JSON serializable
2023-04-20 00:55:01,806 - Service.LoggerContext.get_jobs_from_profile_id() on line 27 - ERROR - Object of type Job is not JSON serializable
2023-04-20 00:55:36,632 - Service.LoggerContext.get_jobs_from_profile_id() on line 27 - ERROR - Object of type Job is not JSON serializable
2023-04-20 00:57:30,968 - Service.LoggerContext.get_jobs_from_profile_id() on line 27 - ERROR - Object of type method is not JSON serializable
2023-04-20 04:56:18,385 - Services.LoggerContext.get_all_profiles() on line 69 - ERROR - Could not determine join condition between parent/child tables on relationship Job.diffs - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
2023-04-20 04:59:46,013 - Services.LoggerContext.get_all_profiles() on line 69 - ERROR - When initializing mapper Mapper[Job(JobsTable)], expression 'scrapeddata' failed to locate a name ("name 'scrapeddata' is not defined"). If this is a class name, consider adding this relationship() to the <class 'Models.DBGateway.Job'> class after both dependent classes have been defined.
2023-04-20 05:01:11,459 - Services.LoggerContext.get_all_profiles() on line 69 - ERROR - When initializing mapper Mapper[Job(JobsTable)], expression 'scraped_data' failed to locate a name ("name 'scraped_data' is not defined"). If this is a class name, consider adding this relationship() to the <class 'Models.DBGateway.Job'> class after both dependent classes have been defined.
2023-04-20 05:02:13,185 - Services.LoggerContext.get_all_profiles() on line 69 - ERROR - When initializing mapper Mapper[Job(JobsTable)], expression 'scraped_data' failed to locate a name ("name 'scraped_data' is not defined"). If this is a class name, consider adding this relationship() to the <class 'Models.DBGateway.Job'> class after both dependent classes have been defined.
